### PR TITLE
changed the web gui to render objects values

### PR DESCRIPTION
**Pull request by henryoswald**
Hey, thanks a lot for creating this project, it is something I really needed.

The web gui is really useful but all of my params are objects so it is hard to see what is in them.
Doing a stringify like this was the path of least resistance, im using it in my fork and find it useful.

### CODE REVIEW

**Comment by baoshan** [comment]
Good suggestion.

**Comment by baoshan** [comment]
The task engine has been tested and deployed throughout last year. But the web GUI is far from maturity (with lots of usability issues). Will improve the GUI when I have time.

**Comment by henryoswald** [comment]
thanks, can you push this to npm please?

we are now running fairy in production. I am keen to help to contribute to the project more.  Do you have any other quick wins you would like to see added to the gui? I am not entirely sure what the schedule button does.

**Comment by baoshan** [comment]
Sorry, NPM release has just been fixed.

Sometimes a task may fail due to the task itself or a buggy worker. When that happens, all tasks of the same group will be halted. Re-schedule will give them another chance.

See: http://baoshan.github.com/fairy/src/fairy.html#section-57

**Pull request merged**
